cargo-features = ["edition"]

[package]
name = "zemeroth"
version = "0.4.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]
license = "MIT/Apache-2.0"
edition = '2018'

[workspace]
members = ["zcomponents", "ggwp-zgui", "ggwp-zscene"]

[dependencies]
ggez = "0.4"
ron = "0.3"
rand = "0.5"
log = "0.4"
env_logger = "0.5"
serde = "1.0"
serde_derive = "1.0"
ggwp-zgui = { path="ggwp-zgui" }
ggwp-zscene = { path="ggwp-zscene" }
zcomponents = { path = "zcomponents" }
